### ISSUE TITLE
AttributeError: Context instance has no attribute 'request'

### ISSUE THREAD

**Issue by lextoumbourou** [thumbor-community/aws#35]
Hi there,

Receiving the following error when trying to use the ``tc_aws.storages.s3_storage`` storage backend  with Thumbor with  ``AUTO_WEBP = True`` configured. 

```
2015-10-23 04:45:39 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/srv/virtualenv/thumbor/local/lib/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
    yielded = next(result)
  File "/srv/virtualenv/thumbor/local/lib/python2.7/site-packages/thumbor/handlers/imaging.py", line 32, in check_image
    exists = yield gen.maybe_future(self.context.modules.storage.exists(kw['image'][:self.context.config.MAX_ID_LENGTH]))
  File "/srv/virtualenv/thumbor/local/lib/python2.7/site-packages/tornado/concurrent.py", line 455, in wrapper
    future.result()
  File "/srv/virtualenv/thumbor/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/srv/virtualenv/thumbor/local/lib/python2.7/site-packages/tornado/concurrent.py", line 443, in wrapper
    result = f(*args, **kwargs)
  File "/srv/virtualenv/thumbor/local/lib/python2.7/site-packages/tc_aws/aws/storage.py", line 102, in exists
    file_abspath = self._normalize_path(path)
  File "/srv/virtualenv/thumbor/local/lib/python2.7/site-packages/tc_aws/aws/storage.py", line 284, in _normalize_path
    if self.is_auto_webp:
  File "/srv/virtualenv/thumbor/local/lib/python2.7/site-packages/tc_aws/aws/storage.py", line 30, in is_auto_webp
    return self.context.config.AUTO_WEBP and self.context.request.accepts_webp
AttributeError: Context instance has no attribute 'request'
```

Running ``tc-aws==2.0.7`` and ``thumbor==5.2.1`` on Ubuntu 14.04.2.

Anyone else seeing this?

**Comment by Bladrak** [comment]
Version 2.0.8 should fix that :)

**Comment by lextoumbourou** [comment]
Much better. Thanks heaps!
