### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by gytisgreitai** [thumbor-community/aws#44]
Hi
not sure if this is thumbor_aws problem, but ...
I'm trying to store unsafe results to s3. If i enable RESULT_STORAGE_STORES_UNSAFE, thumbor crashes:
```
2016-01-14 12:36:06 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 63, in execute_image_operations
    result = yield gen.maybe_future(self.context.modules.result_storage.get())
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 469, in run_callback
    callback(future.result())
  File "/usr/local/lib/python2.7/dist-packages/tc_aws/result_storages/s3_storage.py", line 49, in return_result
    if self._get_error(key):
  File "/usr/local/lib/python2.7/dist-packages/tc_aws/aws/storage.py", line 236, in _get_error
    return response['Error']['Message'] if 'Error' in response else None
```

Source storage (tc_aws.storages.s3_storage) is working fine. My configuration:
```
ALLOWED_SOURCES = ["whitelistedurls"]
ALLOW_UNSAFE_URL = "True"
HTTP_LOADER_FOLLOW_REDIRECTS = "True"
MAX_AGE = 2678400
RESULT_STORAGE_STORES_UNSAFE = "True"
RESULT_STORAGE = "tc_aws.result_storages.s3_storage"
STORAGE = "tc_aws.storages.s3_storage"
TC_AWS_REGION = "eu-west-1"
TC_AWS_RESULT_STORAGE_BUCKET = "my-thumbor-bucket"
TC_AWS_RESULT_STORAGE_ROOT_PATH = "result"
TC_AWS_STORAGE_BUCKET = "my-thumbor-bucket"
TC_AWS_STORAGE_ROOT_PATH = "storage"
TC_AWS_STORAGE_RRS = "False"
TC_AWS_STORAGE_SSE = "False"
```

**Comment by gytisgreitai** [comment]
Never mind, i think there were issues with package versions. Upgrading to tc-aws 2.0.11 and tornado 4.3 fixed the problem
