### ISSUE TITLE
i got this error, is there something configure error

### ISSUE THREAD

**Issue by nosun** [thumbor-community/aws#62]
tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/imaging.py", line 31, in check_image
    exists = yield gen.maybe_future(self.context.modules.storage.exists(kw['image'][:self.context.config.MAX_ID_LENGTH]))
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 473, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 461, in wrapper
    result = f(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tc_aws/aws/storage.py", line 107, in exists
    self.storage.get(file_abspath, callback=return_data)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 473, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 461, in wrapper
    result = f(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tc_aws/aws/bucket.py", line 44, in get
    Key=self._clean_key(path),
  File "/usr/local/lib/python2.7/dist-packages/tornado_botocore/base.py", line 97, in call
    return self._make_api_call(operation_name=self.operation, api_params=kwargs, callback=callback)
  File "/usr/local/lib/python2.7/dist-packages/tornado_botocore/base.py", line 58, in _make_api_call
    request_dict = self.client._convert_to_request_dict(api_params, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 598, in _convert_to_request_dict
    params=api_params, model=operation_model, context=context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/utils.py", line 937, in redirect_from_cache
    context['signing'] = {'bucket': bucket}
TypeError: 'NoneType' object does not support item assignment

**Comment by nosun** [comment]
info: boto3, thumbor 6.1.0

**Comment by ericof** [comment]
@nosun Please pin botocore==1.3.7 to solve this.

**Comment by nosun** [comment]
thanks @ericof , I will have a try

**Comment by teewhey** [comment]
I'm getting similar errors too. Trying to configure the loader to read from S3.

**Comment by Bladrak** [comment]
Seems fixed, closing the issue :) Feel free to re-open if not.

**Comment by ericof** [comment]
"Fix" is to pin botocore?

**Comment by Bladrak** [comment]
@ericof my bad, you're right. I'll try to see how to fix this with latest botocore.

**Comment by NielsKSchjoedt** [comment]
+1

**Comment by aoqfonseca** [comment]
People, 

I believe this issue was fixed at Botocore for last version.  We will try here but you can try also.

**Comment by johntiror** [comment]
it's not fixed, I still have the same issue

**Comment by massipasquesi** [comment]
This package depends on tornado-botocore that depends on botocore==1.2.0 .https://github.com/nanvel/tornado-botocore/issues/8
No possible to use other package with dependency on a more recent version of botocore !!!
No way to use aws-cli if I install tc_aws . Cannot Fix this ?

**Comment by Bladrak** [comment]
We cannot fix this on tc_aws side unless going through a major refactoring. @massipasquesi you could fix your issue by installing either thumbor or aws-cli in a virtualenv

**Comment by massipasquesi** [comment]
Thanks Bladrak for your answer.
I know the solution of using virtualenv but i found it annoying in the scenario of a production server !
I'm building an ec2 instance with a little-customized thumbor service.
I've forked tornado-botocore and i'm trying to make it run with botocore >= 1.5.29.
But during this time I assume that I can't use aws-cli on this server ...
If someone is actually working on this issue, please contact me ! Thanks

**Comment by massipasquesi** [comment]
I tryed to update tornado-botocore botocore dependency
but I think may be the easiest way is to include botornado.1.2.0 in my forked tornado-botornado project and delete dependency.
I check this on my thumbor installation and I will tell you if I will get success.

**Comment by Bladrak** [comment]
@massipasquesi I'm closing this issue given it has been fixed on tornado-botocore's side. Feel free to re-open if need be.
