### ISSUE TITLE
Sentry logging doesn't work with `LOADER=tc_aws.loaders.s3_loader`

### ISSUE THREAD

**Issue by JereMalinen** [thumbor-community/aws#74]
Error with `LOADER=thumbor.loaders.http_loader`:

```
2016-11-10 13:01:05 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 142, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 516, in _fetch
    loader_result = yield self.context.modules.loader.load(self.context, url)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/thumbor/loaders/http_loader.py", line 57, in return_contents
    raise Exception('test')
Exception: test
```

Same error with `LOADER=tc_aws.loaders.s3_loader`:

```
2016-11-10 13:00:35 tornado.application:ERROR Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado/http1connection.py", line 238, in _read_message
    delegate.finish()
  File "/usr/local/lib/python2.7/site-packages/tornado/http1connection.py", line 666, in finish
    return self._delegate.finish()
  File "/usr/local/lib/python2.7/site-packages/tornado/simple_httpclient.py", line 512, in finish
    self.headers["Location"])
  File "/usr/local/lib/python2.7/site-packages/tornado/httputil.py", line 215, in __getitem__
    return self._dict[_normalized_headers[name]]
KeyError: 'Location'
2016-11-10 13:00:35 thumbor:WARNING ERROR retrieving image from S3 bvjzPct.jpg: {'ResponseMetadata': {'HTTPStatusCode': 599, 'HostId': '', 'RequestId': ''}, 'Error': {'Message': '', 'Code': '599'}}
2016-11-10 13:00:35 tornado.access:ERROR 502 GET /unsafe/300x300/i.imgur.com/bvjzPct.jpg (172.17.0.1) 5505.94ms
```

I'm guessing that it has something to do with https://github.com/thumbor-community/aws/blob/master/tc_aws/loaders/s3_loader.py#L82 `logger.warn(...`. Maybe should be at least `logger.error`?

It would be best if `s3_loader` doesn't affect to Thumbor's logging features.

**Comment by aoqfonseca** [comment]
This make sense to me. I believe that we should change to error.  @Bladrak , what you think about ?

**Comment by JereMalinen** [comment]
First message is bit inaccurate or not so perfectly tested. The url was `/unsafe/300x300/i.imgur.com/bvjzPct.jpg`, but `/unsafe/300x300/http%3A//i.imgur.com/bvjzPct.jpg` is better example in this case. And also I should have tested with `TC_AWS_ENABLE_HTTP_LOADER=True`.

So error with those in mind:

```
2016-11-10 14:12:08 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 142, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/thumbor/handlers/__init__.py", line 516, in _fetch
    loader_result = yield self.context.modules.loader.load(self.context, url)
  File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/thumbor/loaders/http_loader.py", line 57, in return_contents
    raise Exception('test')
Exception: test

2016-11-10 14:12:08 thumbor:ERROR [BaseHandler] get_image failed for url `http%3A//i.imgur.com/bvjzPct.jpg`. error: `test`
2016-11-10 14:12:08 tornado.access:ERROR 500 GET /unsafe/300x300/http%3A//i.imgur.com/bvjzPct.jpg (172.17.0.1) 342.13ms
```

And that logs also into Sentry.

However the real production problem was timeout, which wasn't logged into Sentry:

```
Error message
tornado.httpclient:HTTPError: HTTP 599: Timeout while connecting

Stack trace
Traceback (most recent call last):
File "/usr/local/bin/thumbor", line 11, in <module>
File "/usr/local/lib/python2.7/site-packages/thumbor/server.py", line 134, in main
File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 834, in start
File "/usr/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_tornado_r3/ioloop.py", line 31, in _nr_wrapper_IOLoop__run_callback_
File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 604, in _run_callback
File "/usr/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_tornado_r3/util.py", line 204, in transaction_aware
File "/usr/local/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
File "/usr/local/lib/python2.7/site-packages/tornado/simple_httpclient.py", line 307, in _on_timeout
```

**Comment by Bladrak** [comment]
Seems good to log as error, indeed

**Comment by aoqfonseca** [comment]
@JereMalinen 

Seems that was a problem with your infra, is' it right? 

However, we saw that is better follow logs levels from thumbor like you suggest. Then we'll change here for error.

**Comment by JereMalinen** [comment]
@aoqfonseca That error happened only once and the url works perfectly ever since. Url was like `/hash/154x115/smart/http%3A//example.com/image.jpg` and I don't know why it failed. Perhaps some kind of network problem in AWS, but seems unlikely.

Changing to error sounds good to me, thanks for quick responses. :)
