### ISSUE TITLE
S3 storage does not work

### ISSUE THREAD

**Issue by johntiror** [thumbor-community/aws#80]
Hi,

I set thumbor to use S3 also for the storage, but I'm getting the following error:
```
2016-12-06 11:23:12 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/thumbor-6.2.0-py2.7-linux-x86_64.egg/thumbor/handlers/__init__.py", line 142, in get_image
    self.context.request.image_url
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/thumbor-6.2.0-py2.7-linux-x86_64.egg/thumbor/handlers/__init__.py", line 571, in _fetch
    storage.put(url, fetch_result.buffer)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 478, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 466, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tc_aws/storages/s3_storage.py", line 40, in put
    self.set(bytes, self._normalize_path(path), callback=once_written)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 478, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 466, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tc_aws/aws/storage.py", line 80, in set
    callback=callback,
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 478, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/concurrent.py", line 466, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tc_aws/aws/bucket.py", line 106, in put
    session.call(**args)
  File "build/bdist.linux-x86_64/egg/tornado_botocore/base.py", line 97, in call
    return self._make_api_call(operation_name=self.operation, api_params=kwargs, callback=callback)
  File "build/bdist.linux-x86_64/egg/tornado_botocore/base.py", line 60, in _make_api_call
    operation_model=operation_model, request_dict=request_dict, callback=callback)
  File "build/bdist.linux-x86_64/egg/tornado_botocore/base.py", line 54, in _make_request
    request_dict=request_dict, operation_model=operation_model, callback=callback)
  File "build/bdist.linux-x86_64/egg/tornado_botocore/base.py", line 40, in _send_request
    validate_cert=False)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/httpclient.py", line 435, in __init__
    self.body = body
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/httpclient.py", line 480, in body
    self._body = utf8(value)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/escape.py", line 198, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got <type 'instance'>

2016-12-06 11:23:12 thumbor:ERROR [BaseHandler] get_image failed for url `IMG_3314_mod1.JPG`. error: `Expected bytes, unicode, or None; got <type 'instance'>`
2016-12-06 11:23:12 tornado.access:ERROR 500 GET /unsafe/300x200/IMG_3314_mod1.JPG (127.0.0.1) 219.57ms
```

Here my configurations:
STORAGE = 'tc_aws.storages.s3_storage'
TC_AWS_REGION='eu-west-1' # AWS Region
TC_AWS_STORAGE_BUCKET='myapp-thumbor' # S3 bucket for Storage
TC_AWS_STORAGE_ROOT_PATH='storage' # S3 path prefix for Storage bucket
TC_AWS_LOADER_BUCKET='myapp-thumbor' #S3 bucket for loader
TC_AWS_LOADER_ROOT_PATH='loader' # S3 path prefix for Loader bucket

If I use the default storage it works correctly. What am I doing wrong? 
Thanks very much!

**Comment by aoqfonseca** [comment]
@johntiror 

what version are you using?

**Comment by johntiror** [comment]
tc-aws (6.0.3)

pip list

aws-cfn-bootstrap (1.4)
awscli (1.11.24)
Babel (0.9.4)
backports-abc (0.5)
backports.ssl-match-hostname (3.4.0.2)
boto (2.42.0)
boto3 (1.4.2)
botocore (1.4.7)
certifi (2016.9.26)
chardet (2.0.1)
cloud-init (0.7.6)
colorama (0.2.5)
configobj (4.7.2)
derpconf (0.8.1)
docutils (0.11)
ecdsa (0.11)
futures (3.0.3)
iniparse (0.3.1)
Jinja2 (2.7.2)
jmespath (0.7.1)
jsonpatch (1.2)
jsonpointer (1.0)
kitchen (1.1.1)
libthumbor (1.3.2)
lockfile (0.8)
MarkupSafe (0.11)
meld3 (1.0.2)
paramiko (1.15.1)
pexif (0.15)
PIL (1.1.6)
Pillow (3.4.2)
pip (9.0.1)
ply (3.4)
pyasn1 (0.1.7)
pycrypto (2.6.1)
pycurl (7.19.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pystache (0.5.3)
python-daemon (1.5.2)
python-dateutil (2.1)
pytz (2016.7)
pyxattr (0.5.0)
PyYAML (3.10)
requests (1.2.3)
rsa (3.4.1)
s3transfer (0.1.9)
setuptools (28.8.0)
simplejson (3.6.5)
singledispatch (3.4.0.3)
six (1.8.0)
statsd (3.2.1)
supervisor (3.3.1)
tc-aws (6.0.3)
thumbor (6.2.0)
tornado (4.4.2)
tornado-botocore (1.0.2)
urlgrabber (3.9.1)
urllib3 (1.8.2)
virtualenv (12.0.7)
yum-metadata-parser (1.1.4)

Thanks

**Comment by aoqfonseca** [comment]
@johntiror 

Just try put all configs recommended.  I'm reproduce you scenario to get this error but unitl now nothing..... 


Look readme from project to know what you need.  If this doesn't work post here and we try to debug with you what happens. Ok?

**Comment by Bladrak** [comment]
@johntiror did you put the correct bucket names in the ``TC_AWS_STORAGE_BUCKET`` and ``TC_AWS_LOADER_BUCKET`` settings?

**Comment by aoqfonseca** [comment]
@johntiror 
Any news about this issue? Have you managed the problem with yours configs?

**Comment by johntiror** [comment]
No, but now I switched to a docker image I found on dockerhub. I'm not using S3 as a storage anymore. Thanks

Inviato da iPhone

**Comment by Bladrak** [comment]
Ok, I'm closing the issue then, feel free to re-open if you need more support.
