### ISSUE TITLE
Using Smart/face detection dos not work

### ISSUE THREAD

**Issue by benzon** [thumbor-community/aws#82]
2016-12-13 02:27:55 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 211, in get_image
    self.filters_runner.apply_filters(thumbor.filters.PHASE_AFTER_LOAD, transform)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 209, in transform
    self.context.transformer.transform(after_transform_cb)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 102, in transform
    self.smart_detect()
  File "/usr/local/lib/python2.7/dist-packages/thumbor/transformer.py", line 151, in smart_detect
    self.do_smart_detection().result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    self._check_done()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 316, in _check_done
    raise Exception("DummyFuture does not support blocking for results")
Exception: DummyFuture does not support blocking for results
2016-12-13 02:27:55 thumbor:WARNING [AwsStorage] s3 key not found at 234e6915e9c52302.29448476.detectors.txt

**Comment by Bladrak** [comment]
This seems to be due to the fact that tc_aws can't find the image you're requesting.

**Comment by benzon** [comment]
I did a small work around in a file in Thumbor and got it working, since it found the files with out the smart filter.

**Comment by Bladrak** [comment]
Ok, can we close this issue then?

**Comment by thewhit** [comment]
@benzon Can you elaborate on the small workaround you did to get detection working?
