### ISSUE TITLE
Problem with unicode chars in path?

### ISSUE THREAD

**Issue by smagnaschi** [thumbor-community/aws#95]
Taken the S3 object with a path containing non ascii chars like

`/img/foto/wikipedia/20140802-350-See-Rock_Festival_2014-Twisted_Sister-John_"Jay_Jay"_French_and_Daniel_„Dee“_Snider.jpg`

that has a public url like this

`https://s3.eu-central-1.amazonaws.com/rockol-img-test/img/foto/wikipedia/20140802-350-See-Rock_Festival_2014-Twisted_Sister-John_%22Jay_Jay%22_French_and_Daniel_%E2%80%9EDee%E2%80%9C_Snider.jpg`

I keep on getting error using the S3 loader like this

```
2017-07-28 12:57:20 thumbor:ERROR [BaseHandler] get_image failed for url `rockol-img/img/foto/wikipedia/20140802-350-See-Rock_Festival_2014-Twisted_Sister-John_%22Jay_Jay%22_French_and_Daniel_%E2%80%9EDee%E2%80%9C_Snider.jpg`. error: `'ascii' codec can't decode byte 0xe2 in position 103: ordinal not in range(128)`
2017-07-28 12:57:20 tornado.access:ERROR 500 GET /SElOX3XQ77skl8gH9IsXx8FbIks=/57x552/smart/rockol-img/img/foto/wikipedia/20140802-350-See-Rock_Festival_2014-Twisted_Sister-John_%22Jay_Jay%22_French_and_Daniel_%E2%80%9EDee%E2%80%9C_Snider.jpg (127.0.0.1) 5.74ms
```

I tried different solutions, such as encoding the path but I cannot make it work. The Http loader instead runs just fine and succeeds in getting the right url despite the non ascii chars.

What am I doing wrong? This happens for all the non ascii chars.

**Comment by aoqfonseca** [comment]
Can you share more logs about this problem?

**Comment by codywilbourn** [comment]
I believe I've run into a similar problem trying to encode the ® character (`%C2%AE` when url-encoded) embedded in an image url I'm trying to resize.

Passing the url-encoded character in the requested url I get the following trace
```
2017-10-25 15:47:03 thumbor:DEBUG METRICS: inc: response.count:1
2017-10-25 15:47:03 botocore.client:DEBUG Registering retry handlers for service: s3
2017-10-25 15:47:03 botocore.hooks:DEBUG Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f9b011d0a28>
2017-10-25 15:47:03 botocore.hooks:DEBUG Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f9b011d0848>
2017-10-25 15:47:03 botocore.args:DEBUG The s3 config key is not a dictionary type, ignoring its value of: None
2017-10-25 15:47:03 botocore.endpoint:DEBUG Setting s3 timeout as (60, 60)
2017-10-25 15:47:03 botocore.client:DEBUG Defaulting to S3 virtual host style addressing with path style addressing fallback.
2017-10-25 15:47:03 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/imaging.py", line 31, in check_image
    exists = yield gen.maybe_future(self.context.modules.storage.exists(kw['image'][:self.context.config.MAX_ID_LENGTH]))
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 483, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 471, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tc_aws/aws/storage.py", line 108, in exists
    self.storage.get(file_abspath, callback=return_data)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 483, in wrapper
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 471, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tc_aws/aws/bucket.py", line 49, in get
    Key=self._clean_key(path),
  File "/usr/local/lib/python2.7/dist-packages/tc_aws/aws/bucket.py", line 129, in _clean_key
    logger.debug('Cleaning key: {path}'.format(path=path))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 76: ordinal not in range(128)
```
https://github.com/thumbor-community/aws/blob/45e9f461f00ab1b9c6fff4a171f03ab5ff043d5f/tc_aws/aws/bucket.py

The requestor will hang indefinitely until a timeout is reached by the client or the web server (nginx, load balancer).

I tested this on Thumbor 6.3.2 / tc-aws 6.0.4

**Comment by aoqfonseca** [comment]
Thanks! We will see and keep you inform.

**Comment by codywilbourn** [comment]
I investigated further, and it appears that a workaround is that you can just update this line `logger.debug('Cleaning key: {path}'.format(path=path))` to be `logger.debug('Cleaning key: {path!r}'.format(path=path))`, so that you use the representation of the object, which won't contain the unicode characters. Further down you'll also have to do that to `logger.debug('Cleansed key: {key}'.format(key=key))` as well. No other changes were needed to store the image in S3 or load the resized image from S3.

**Comment by Bladrak** [comment]
Closing as the PR has been merged :)
